<div class="wrap">
<?php
function odude_get_page_by_name($pagename)
{
$pages = get_pages();
foreach ($pages as $page) if ($page->post_name == $pagename) return $page;
return false;
}

 $settings = get_option('_odudes_settings');
 $shoppingurl=get_site_url()."/product";
 
 $section_page = odude_get_page_by_name('section');
if (!empty($section_page)) 
{
	$section="It's Good. Section page exisit.";
} 
else
	{
		$section="Section page not found.<br>Create it with slug name as <b>section</b> only if you want dynamic product list generated by ODudeShop and don't want to use theme template file.<br>Use shortcode as [odudes-all-section perrow=\"3\" perpage=\"9\" orderby=\"date\" layout=\"list\"] ";
}
 $product_page = odude_get_page_by_name('product');
if (!empty($product_page)) 
{
	$product="Product page with slug product exisit.<br>It is recommended that there shouldn't be any page with this slug name. <br>This page is automatically generated.";
} 
else
	{
		$product="It's good. No product page found.";
}

?>
<h3>Checking System Details: ODudeShop</h3>
<b>Shopping URL</b> : <?php echo $shoppingurl; ?><br>
<b>Currency Sign</b>: <?php echo $settings['cur_sign']; ?><br>
<b>Currency Code</b>: <?php echo $settings['cur_code']; ?><br>
<b>Section Page</b>: <?php echo $section; ?><br>
<b>Product Page</b>: <?php echo $product; ?><br>
<hr>
<h3>Updates in 1.1.5 - 1st Feb 2016</h3>
<ul>
<li> Added Dashboard (For updated details and system check.)
<li> New hover layout added (Change layout at displaying product shortcode)
<li> Dynamic section page. (Now no need to create page for each category.)
</ul>

<hr><b>Visit <a href="http://odude.com/odudeshop/" target="_blank">ODude.com</a> for help</b>
</div>